# Generated by Django 4.2.5 on 2024-03-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='description',
            field=models.CharField(default='city test', max_length=200),
            preserve_default=False,
        ),
    ]
