# Generated by Django 5.0.3 on 2024-03-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_rename_lantitude_cities_latitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='longitude',
        ),
    ]
