# Generated by Django 5.0.3 on 2024-03-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0006_remove_cities_latitude_remove_cities_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
